version: '3.7'
services:

  mers-face-detection-and-classification:
    build:
      context: ./mers-face-detection-and-classification/
      dockerfile: Dockerfile.mers-face-detection-and-classification
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/mers-face-detection-and-classification
    container_name: application-mers-face-detection-and-classification
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY-:0}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/mers-user/.Xauthority:rw
      - ./common/:/home/mers-user/common/
      - ../media/:/home/mers-user/media
      - /usr/share/glib-2.0/schemas/gschemas.compiled:/usr/share/glib-2.0/schemas/gschemas.compiled

  mers-face-detection-multichannel:
    build:
      context: ./mers-face-detection-multichannel/
      dockerfile: Dockerfile.mers-face-detection-multichannel
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/mers-face-detection-multichannel
    container_name: application-mers-face-multichannel
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY-:0}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/mers-user/.Xauthority:rw
      - ./common/:/home/mers-user/common/
      - ../media/:/home/mers-user/media
      - /usr/share/glib-2.0/schemas/gschemas.compiled:/usr/share/glib-2.0/schemas/gschemas.compiled
