FROM xe1gyq/openvino

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ARG OPENVINO_INSTALL=/opt/intel/openvino

ENV TIMEZONE America/Mexico_City
USER root
ENV HOME_USER /home/user
ENV OPENVINO_RELEASE 80e06c965a5a562f9f1df2782187e7f74b02e306

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl-dev \
    git \
    libboost-dev \
    libboost-log-dev&& \
    rm -rf /var/lib/apt/lists/*

ADD --chown=1000:1000 main.sh /home/user/
RUN /bin/bash -c 'chmod +x /home/user/main.sh'

RUN chown -R user /home/user
USER user

WORKDIR /opt/intel/openvino/deployment_tools/tools/model_downloader
RUN sudo ./downloader.py --name vehicle-license-plate-detection-barrier-0106 && \
    sudo ./downloader.py --name vehicle-detection-adas-0002 && \
    sudo ./downloader.py --name vehicle-attributes-recognition-barrier-0039 && \
    sudo ./downloader.py --name person-vehicle-bike-detection-crossroad-0078 && \
    sudo ./downloader.py --name person-detection-retail-0013 && \
    sudo ./downloader.py --name pedestrian-and-vehicle-detector-adas-0001 && \
    sudo ./downloader.py --name pedestrian-detection-adas-0002

WORKDIR /home/user

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh && \
    git clone https://github.com/incluit/OpenVino-For-SmartCity.git && \
    cd OpenVino-For-SmartCity/ && \
    git reset --hard $OPENVINO_RELEASE && \
    mkdir build && \
    cd build && \
    bash ../scripts/download_models.sh && \
    source ../scripts/setupenv.sh && \
    cmake -DCMAKE_BUILD_TYPE=Release ../ && \
    make"

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh"
RUN echo "source $OPENVINO_INSTALL/bin/setupvars.sh" >> /home/user/.bashrc

ARG DEVICE
ENV DEVICE="${DEVICE}"

ARG TARGET
ENV TARGET="${TARGET}"

ENTRYPOINT ["/bin/bash"]
#ENTRYPOINT ["/home/user/main.sh"]
#CMD ["/home/user/main.sh", "${DEVICE}", "${TARGET}"]
