version: '3.7'
services:

  gstreamer:
    build:
      context: ./gstreamer/
      dockerfile: Dockerfile.gstreamer
      args:
        - CAMERA_IDENTIFICATION=${CAMERA_IDENTIFICATION:-camera-01}
        - VIDEO_CAPTURE=${VIDEO_CAPTURE:-http://172.17.0.1:9081/?action=stream}
        - SINK_HOST_IP=${SINK_HOST_IP:-172.17.0.1}
        - SINK_HOST_PORT=${SINK_HOST_PORT:-5001}
    image: application/gstreamer
    container_name: application-gstreamer
    privileged: true
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - CAMERA_IDENTIFICATION=${CAMERA_IDENTIFICATION:-camera-01}
      - VIDEO_CAPTURE=${VIDEO_CAPTURE:-http://172.17.0.1:9081/?action=stream}
      - SINK_HOST_IP=${SINK_HOST_IP:-172.17.0.1}
      - SINK_HOST_PORT=${SINK_HOST_PORT:-5001}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  haarcascades:
    build:
      context: ./haarcascades/
      dockerfile: Dockerfile.haarcascades
      args:
        - SERVICE_NAME=${SERVICE_NAME:-HaarCascades}
        - VIDEO_CAPTURE=${VIDEO_CAPTURE:-http://172.17.0.1:9081/?action=stream}
        - SINK_HOST_IP=${SINK_HOST_IP:-172.17.0.1}
        - SINK_HOST_PORT=${SINK_HOST_PORT:-5001}
    image: application/haarcascades
    container_name: application-haarcascades
    privileged: true
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - SERVICE_NAME=${SERVICE_NAME:-HaarCascades}
      - VIDEO_CAPTURE=${VIDEO_CAPTURE:-http://172.17.0.1:9081/?action=stream}
      - SINK_HOST_IP=${SINK_HOST_IP:-172.17.0.1}
      - SINK_HOST_PORT=${SINK_HOST_PORT:-5001}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  opencv-mobilenet-ssd-python:
    build:
      context: ./opencv/mobilenet-ssd-python/
      dockerfile: Dockerfile.mobilenet-ssd-python
    image: application/openrtist
    container_name: application-opencv-mobilenet-ssd-python
    privileged: true
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - ID=${ID:-camera-01}
    network_mode: host
    devices:
      - /dev
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix

  openrtist:
    build:
      context: ./openrtist/
      dockerfile: Dockerfile.openrtist
    image: application/openrtist
    container_name: application-openrtist
    privileged: true
    restart: on-failure
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
    network_mode: host
    ports:
      - 9098:9098
      - 9111:9111
      - 22222:22222
      - 8021:8021
    devices:
      - /dev
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
