FROM sysstacks/mers-clearlinux

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ENV TIMEZONE America/Mexico_City
ENV USER root

ADD --chown=1000:1000 main.sh /home/mers-user
RUN /bin/bash -c 'chmod +x /home/mers-user/main.sh'
ADD --chown=1000:1000 face_detection_and_classification_publish_mqtt.sh /home/mers-user
RUN /bin/bash -c 'chmod +x /home/mers-user/face_detection_and_classification_publish_mqtt.sh'

WORKDIR /home/mers-user

ARG TARGET
ENV TARGET="${TARGET}"

ARG INPUT
ENV INPUT="${INPUT}"

ENTRYPOINT ["/home/mers-user/main.sh"]
CMD ["/home/mers-user/main.sh", "${TARGET}", "${INPUT}"]
