FROM gst-video-analytics:latest

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ENV TIMEZONE America/Mexico_City
ENV USER root

ADD --chown=1000:1000 main.sh /root/
RUN /bin/bash -c 'chmod +x /root/main.sh'
ADD --chown=1000:1000 face_detection_and_classification_publish_mqtt.sh /root/
RUN /bin/bash -c 'chmod +x /root/face_detection_and_classification_publish_mqtt.sh'

WORKDIR /root

ARG TARGET
ENV TARGET="${TARGET}"

ARG INPUT
ENV INPUT="${INPUT}"

ENTRYPOINT ["/root/main.sh"]
CMD ["/root/main.sh", "${TARGET}", "${INPUT}"]
