version: '3.7'
services:

  restricted-zone-notifier-cpp:
    build:
      context: ./restricted-zone-notifier-cpp/
      dockerfile: Dockerfile.restricted-zone-notifier-cpp
      args:
        - TARGET=${TARGET:-CPU}
    image: application/restricted-zone-notifier-cpp
    container_name: application-restricted-zone-notifier-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - TARGET=${TARGET:-CPU}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  shopper-gaze-monitor-cpp:
    build:
      context: ./shopper-gaze-monitor-cpp/
      dockerfile: Dockerfile.shopper-gaze-monitor-cpp
      args:
        - TARGET=${TARGET:-CPU}
    image: application/shopper-gaze-monitor-cpp
    container_name: application-shopper-gaze-monitor-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - TARGET=${TARGET:-CPU}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  shopper-mood-monitor-cpp:
    build:
      context: ./shopper-mood-monitor-cpp/
      dockerfile: Dockerfile.shopper-mood-monitor-cpp
      args:
        - TARGET=${TARGET:-CPU}
    image: application/shopper-mood-monitor-cpp
    container_name: application-shopper-mood-monitor-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - TARGET=${TARGET:-CPU}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  parking-lot-counter-cpp:
    build:
      context: ./parking-lot-counter-cpp/
      dockerfile: Dockerfile.parking-lot-counter-cpp
      args:
        - TARGET=${TARGET:-CPU}
    image: application/parking-lot-counter-cpp
    container_name: application-parking-lot-counter-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - TARGET=${TARGET:-CPU}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media
