version: '3.7'
services:

  interactive-face-recognition-demo-python:
    build:
      context: ./interactive-face-recognition-demo-python/
      dockerfile: Dockerfile.interactive-face-recognition-demo-python
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/interactive-face-recognition-demo-python
    hostname: ${HOSTNAME}
    container_name: application-interactive-face-recognition-demo-python
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - STATSD_SERVER=${STATSD_SERVER:-172.17.0.1}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media
      - ../../media/people/:/tmp/demo

  multicamera-multiperson-demo-python:
    build:
      context: ./multicamera-multiperson-demo-python/
      dockerfile: Dockerfile.multicamera-multiperson-demo-python
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/multicamera-multiperson-demo-python
    hostname: ${HOSTNAME}
    container_name: application-multicamera-multiperson-demo-python
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - STATSD_SERVER=${STATSD_SERVER:-172.17.0.1}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  image-classification-python:
    build:
      context: ./image-classification-python/
      dockerfile: Dockerfile.image-classification-python
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/image-classification-python
    hostname: ${HOSTNAME}
    container_name: application-image-classification-python
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - MODEL=${MODEL:-ResNet50}
      - STATSD_SERVER=${STATSD_SERVER:-172.17.0.1}
    network_mode: host
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  object-detection-ssd-python:
    build:
      context: ./object-detection-ssd-python/
      dockerfile: Dockerfile.object-detection-ssd-python
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/object-detection-ssd-python
    hostname: ${HOSTNAME}
    container_name: application-object-detection-ssd-python
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - STATSD_SERVER=${STATSD_SERVER:-172.17.0.1}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  object-size-detector-cpp:
    build:
      context: ./object-size-detector-cpp/
      dockerfile: Dockerfile.object-size-detector-cpp
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/object-size-detector-cpp
    hostname: ${HOSTNAME}
    container_name: application-object-size-detector-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  openvino-for-smartcity:
    build:
      context: ./openvino-for-smartcity/
      dockerfile: Dockerfile.openvino-for-smartcity
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/openvino-for-smartcity
    hostname: ${HOSTNAME}
    container_name: application-openvino-for-smartcity
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix

  parking-lot-counter-cpp:
    build:
      context: ./parking-lot-counter-cpp/
      dockerfile: Dockerfile.parking-lot-counter-cpp
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/parking-lot-counter-cpp
    hostname: ${HOSTNAME}
    container_name: application-parking-lot-counter-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - MQTT_SERVER=${MQTT_SERVER:-172.17.0.1}
      - STATSD_SERVER=${STATSD_SERVER:-172.17.0.1}
      - ENTRANCE=${ENTRANCE:-right}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  restricted-zone-notifier-cpp:
    build:
      context: ./restricted-zone-notifier-cpp/
      dockerfile: Dockerfile.restricted-zone-notifier-cpp
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/restricted-zone-notifier-cpp
    hostname: ${HOSTNAME}
    container_name: application-restricted-zone-notifier-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - MQTT_SERVER=${MQTT_SERVER:-172.17.0.1}
      - STATSD_SERVER=${STATSD_SERVER:-172.17.0.1}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  restricted-zone-notifier-python:
    build:
      context: ./restricted-zone-notifier-python/
      dockerfile: Dockerfile.restricted-zone-notifier-python
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/restricted-zone-notifier-python
    hostname: ${HOSTNAME}
    container_name: application-restricted-zone-notifier-python
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - MODEL=${MODEL:-person-detection-retail-0013}
      - THRESHOLD=${THRESHOLD:-.75}
      - MQTT_SERVER=${MQTT_SERVER:-172.17.0.1}
      - STATSD_SERVER=${STATSD_SERVER:-172.17.0.1}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  shopper-gaze-monitor-python:
    build:
      context: ./shopper-gaze-monitor-python/
      dockerfile: Dockerfile.shopper-gaze-monitor-python
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/shopper-gaze-monitor-python
    hostname: ${HOSTNAME}
    container_name: application-shopper-gaze-monitor-python
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  #safety-gear-detector-cpp:
  #  build:
  #    context: ./safety-gear-detector-cpp/
  #    dockerfile: Dockerfile.safety-gear-detector-cpp
  #    args:
  #      - TARGET=${TARGET:-CPU}
  #      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
  #  image: application/safety-gear-detector-cpp
  #  hostname: ${HOSTNAME}
  #  container_name: application-safety-gear-detector-cpp
  #  privileged: true
  #  restart: always
  #  environment:
  #    - TZ=America/Mexico_City
  #    - DISPLAY=${DISPLAY:-:0}
  #    - TARGET=${TARGET:-CPU}
  #    - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
  #  network_mode: host
  #  ports:
  #    - 5001:5001
  #  devices:
  #    - /dev
  #  volumes:
  #    - /etc/localtime:/etc/localtime:ro
  #    - /tmp/.X11-unix:/tmp/.X11-unix
  #    - ../media/:/home/user/media

  #shopper-gaze-monitor-cpp:
  #  build:
  #    context: ./shopper-gaze-monitor-cpp/
  #    dockerfile: Dockerfile.shopper-gaze-monitor-cpp
  #    args:
  #      - TARGET=${TARGET:-CPU}
  #      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
  #  image: application/shopper-gaze-monitor-cpp
  #  hostname: ${HOSTNAME}
  #  container_name: application-shopper-gaze-monitor-cpp
  #  privileged: true
  #  restart: always
  #  environment:
  #    - TZ=America/Mexico_City
  #    - DISPLAY=${DISPLAY:-:0}
  #    - TARGET=${TARGET:-CPU}
  #    - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
  #  network_mode: host
  #  ports:
  #    - 5001:5001
  #  devices:
  #    - /dev
  #  volumes:
  #    - /etc/localtime:/etc/localtime:ro
  #    - /tmp/.X11-unix:/tmp/.X11-unix
  #    - ../media/:/home/user/media

  shopper-mood-monitor-cpp:
    build:
      context: ./shopper-mood-monitor-cpp/
      dockerfile: Dockerfile.shopper-mood-monitor-cpp
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/shopper-mood-monitor-cpp
    hostname: ${HOSTNAME}
    container_name: application-shopper-mood-monitor-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media
