version: '3.7'
services:

  object-size-detector-cpp:
    build:
      context: ./object-size-detector-cpp/
      dockerfile: Dockerfile.object-size-detector-cpp
      args:
        - TARGET=${TARGET:-CPU}
    image: application/object-size-detector-cpp
    container_name: application-object-size-detector-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - TARGET=${TARGET:-CPU}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  openvino-for-smartcity:
    build:
      context: ./openvino-for-smartcity/
      dockerfile: Dockerfile.openvino-for-smartcity
      args:
        - TARGET=${TARGET:-CPU}
    image: application/openvino-for-smartcity
    container_name: application-openvino-for-smartcity
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - TARGET=${TARGET:-CPU}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix

  restricted-zone-notifier-cpp:
    build:
      context: ./restricted-zone-notifier-cpp/
      dockerfile: Dockerfile.restricted-zone-notifier-cpp
      args:
        - TARGET=${TARGET:-CPU}
    image: application/restricted-zone-notifier-cpp
    container_name: application-restricted-zone-notifier-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - TARGET=${TARGET:-CPU}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  restricted-zone-notifier-python:
    build:
      context: ./restricted-zone-notifier-python/
      dockerfile: Dockerfile.restricted-zone-notifier-python
      args:
        - TARGET=${TARGET:-CPU}
    image: application/restricted-zone-notifier-python
    container_name: application-restricted-zone-notifier-python
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - TARGET=${TARGET:-CPU}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  safety-gear-detector-cpp:
    build:
      context: ./safety-gear-detector-cpp/
      dockerfile: Dockerfile.safety-gear-detector-cpp
      args:
        - TARGET=${TARGET:-CPU}
    image: application/safety-gear-detector-cpp
    container_name: application-safety-gear-detector-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - TARGET=${TARGET:-CPU}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  shopper-gaze-monitor-cpp:
    build:
      context: ./shopper-gaze-monitor-cpp/
      dockerfile: Dockerfile.shopper-gaze-monitor-cpp
      args:
        - TARGET=${TARGET:-CPU}
    image: application/shopper-gaze-monitor-cpp
    container_name: application-shopper-gaze-monitor-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - TARGET=${TARGET:-CPU}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  shopper-mood-monitor-cpp:
    build:
      context: ./shopper-mood-monitor-cpp/
      dockerfile: Dockerfile.shopper-mood-monitor-cpp
      args:
        - TARGET=${TARGET:-CPU}
    image: application/shopper-mood-monitor-cpp
    container_name: application-shopper-mood-monitor-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - TARGET=${TARGET:-CPU}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media

  parking-lot-counter-cpp:
    build:
      context: ./parking-lot-counter-cpp/
      dockerfile: Dockerfile.parking-lot-counter-cpp
      args:
        - TARGET=${TARGET:-CPU}
    image: application/parking-lot-counter-cpp
    container_name: application-parking-lot-counter-cpp
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=:0
      - TARGET=${TARGET:-CPU}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../media/:/home/user/media
