FROM xe1gyq/openvino

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ARG OPENVINO_INSTALL=/opt/intel/openvino
ARG IIKIM_BRANCH=iikim

ENV TIMEZONE America/Mexico_City
USER root
ENV HOME_USER /home/user

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends \
    git && \
    rm -rf /var/lib/apt/lists/*

RUN chown -R user /home/user
USER user
WORKDIR /home/user

RUN wget -O ~/video.mp4 https://raw.githubusercontent.com/intel-iot-devkit/sample-videos/master/face-demographics-walking-and-pause.mp4 && \
    git clone -b ${IIKIM_BRANCH} https://github.com/bosques-urbanos/open_model_zoo.git

RUN cd /opt/intel/openvino/deployment_tools/tools/model_downloader && \
    python3 downloader.py --name mobilenet-ssd -o ~/

RUN cd /opt/intel/openvino/deployment_tools/model_optimizer/ && \
    pip3 install --upgrade pip && \
    pip3 install -r requirements_caffe.txt && \
    pip3 install coverage m2r pyenchant pylint Sphinx safety test-generator && \
    ./mo_caffe.py \
      --input_shape=[1,3,224,224] \
      --mean_values=data[104.0,117.0,123.0] \
      --input_model=/home/user/public/mobilenet-ssd/mobilenet-ssd.caffemodel \
      --input_proto=/home/user/public/mobilenet-ssd/mobilenet-ssd.prototxt \
      --output_dir=/home/user/

ADD --chown=1000:1000 main.sh /home/user/
RUN /bin/bash -c 'chmod +x /home/user/main.sh'

ARG TARGET
ENV TARGET="${TARGET}"

ARG INPUT
ENV INPUT="${INPUT}"

ARG STATSD_SERVER
ENV STATSD_SERVER="${STATSD_SERVER}"

ENTRYPOINT ["/home/user/main.sh"]
CMD ["/home/user/main.sh", "${TARGET}", "${INPUT}", "${STATSD_SERVER}"]
