version: '3.7'
services:

  face-detection-and-classification:
    build:
      context: ./face-detection-and-classification/
      dockerfile: Dockerfile.face-detection-and-classification
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/face-detection-and-classification
    container_name: application-face-detection-and-classification
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - MODELS_PATH=${MODELS_PATH:-"/root/intel_models:/root/models"}
      - VIDEO_EXAMPLES_DIR=${VIDEO_EXAMPLES_DIR:-/root/video-examples}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - ../media/:/home/user/media
      - $GVA_PATH:/root/gst-video-analytics
      - $INTEL_MODELS_PATH:/root/intel_models
      - $MODELS_PATH:/root/models
      - $VIDEO_EXAMPLES_PATH:/root/video-examples
      - /usr/share/glib-2.0/schemas/gschemas.compiled:/usr/share/glib-2.0/schemas/gschemas.compiled

  face-detection-and-classification-publish-mqtt:
    build:
      context: ./face-detection-and-classification-publish-mqtt/
      dockerfile: Dockerfile.face-detection-and-classification-publish-mqtt
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/face-detection-and-classification-publish-mqtt
    container_name: application-face-detection-and-classification-publish-mqtt
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - MODELS_PATH=${MODELS_PATH:-"/root/intel_models:/root/models"}
      - VIDEO_EXAMPLES_DIR=${VIDEO_EXAMPLES_DIR:-/root/video-examples}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - ../media/:/home/user/media
      - $GVA_PATH:/root/gst-video-analytics
      - $INTEL_MODELS_PATH:/root/intel_models
      - $MODELS_PATH:/root/models
      - $VIDEO_EXAMPLES_PATH:/root/video-examples
      - /usr/share/glib-2.0/schemas/gschemas.compiled:/usr/share/glib-2.0/schemas/gschemas.compiled

  face-detection-multichannel:
    build:
      context: ./face-detection-multichannel/
      dockerfile: Dockerfile.face-detection-multichannel
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/face-detection-multichannel
    container_name: application-face-detection-multichannel
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - MODELS_PATH=${MODELS_PATH:-"/root/intel_models:/root/models"}
      - VIDEO_EXAMPLES_DIR=${VIDEO_EXAMPLES_DIR:-/root/video-examples}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - ../media/:/home/user/media
      - $GVA_PATH:/root/gst-video-analytics
      - $INTEL_MODELS_PATH:/root/intel_models
      - $MODELS_PATH:/root/models
      - $VIDEO_EXAMPLES_PATH:/root/video-examples
      - /usr/share/glib-2.0/schemas/gschemas.compiled:/usr/share/glib-2.0/schemas/gschemas.compiled

  vehicle-detection-publish-mqtt:
    build:
      context: ./vehicle-detection-publish-mqtt/
      dockerfile: Dockerfile.vehicle-detection-publish-mqtt
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/vehicle-detection-publish-mqtt
    container_name: application-vehicle-detection-publish-mqtt
    privileged: true
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY}
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - MODELS_PATH=${MODELS_PATH:-"/root/intel_models:/root/models"}
      - VIDEO_EXAMPLES_DIR=${VIDEO_EXAMPLES_DIR:-/root/video-examples}
    network_mode: host
    ports:
      - 5001:5001
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - ../media/:/home/user/media
      - $GVA_PATH:/root/gst-video-analytics
      - $INTEL_MODELS_PATH:/root/intel_models
      - $MODELS_PATH:/root/models
      - $VIDEO_EXAMPLES_PATH:/root/video-examples
      - /usr/share/glib-2.0/schemas/gschemas.compiled:/usr/share/glib-2.0/schemas/gschemas.compiled
