FROM clearlinux/stacks-dlrs_2-mkl

RUN pip install opencv-python paho-mqtt

RUN curl -o /workspace/video.mp4 https://raw.githubusercontent.com/intel-iot-devkit/sample-videos/master/face-demographics-walking-and-pause.mp4 && \
    git clone https://github.com/bosques-urbanos/open_model_zoo.git && \
    cd ~/workspace/open_model_zoo/ && \
    git checkout -b 2019 origin/2019 && \
    cd model_downloader && \
    python3 downloader.py --name person-detection-retail-0013 -o ~/ && \
    python3 downloader.py --name person-reidentification-retail-0031 -o ~/

RUN cd ~/workspace/open_model_zoo/ && \
    git checkout master && \
    cd demos/python_demos/multi_camera_multi_person_tracking/ && \
    pip3 install -r requirements.txt && \
    pip3 install queuelib && \
    pip3 install statsd

ADD --chown=1000:1000 main.sh /workspace/
RUN /bin/bash -c 'chmod +x /workspace/main.sh'

ARG TARGET
ENV TARGET="${TARGET}"

ARG INPUT
ENV INPUT="${INPUT}"

ENTRYPOINT ["/workspace/main.sh"]
CMD ["/home/user/main.sh", "${TARGET}", "${INPUT}"]
