FROM xe1gyq/openvino

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ARG OPENVINO_INSTALL=/opt/intel/openvino

ENV TIMEZONE America/Mexico_City
USER root
ENV HOME_USER /home/user

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl-dev \
    git && \
    rm -rf /var/lib/apt/lists/*

RUN chown -R user /home/user
USER user
WORKDIR /home/user

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh -pyver 3.5 && \
    git clone --single-branch -b OpenVINO_2019_R3 https://github.com/xe1gyq/restricted-zone-notifier-python.git && \
    cd restricted-zone-notifier-python/ && \
    bash ./setup.sh"

ADD --chown=1000:1000 main.sh /home/user/
RUN /bin/bash -c 'chmod +x /home/user/main.sh'

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh"
RUN echo "source $OPENVINO_INSTALL/bin/setupvars.sh -pyver 3.5" >> /home/user/.bashrc

ARG TARGET
ENV TARGET="${TARGET}"

ARG INPUT
ENV INPUT="${INPUT}"

ARG MQTT_SERVER
ENV MQTT_SERVER="${MQTT_SERVER}"

ARG STATSD_SERVER
ENV STATSD_SERVER="${STATSD_SERVER}"

ENTRYPOINT ["/home/user/main.sh"]
CMD ["/home/user/main.sh", "${TARGET}", "${INPUT}", "${MQTT_SERVER}", "${STATSD_SERVER}"]
