FROM clearlinux/stacks-mers

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ENV TIMEZONE America/Mexico_City
ARG IIKIM_MERS_BRANCH=2019
ARG IIKIM_GST_BRANCH=v0.7
ARG HOME=/home/mers-user/
ARG MODELS=$HOME/models/

WORKDIR $HOME
USER 0

RUN swupd bundle-add desktop-dev && \
    pip install pyyaml

USER mers-user
RUN curl -o $HOME/video.mp4 \
      https://raw.githubusercontent.com/intel-iot-devkit/sample-videos/master/face-demographics-walking-and-pause.mp4 && \
    git clone -b ${IIKIM_MERS_BRANCH} https://github.com/bosques-urbanos/open_model_zoo.git && \
    cd open_model_zoo/ && \
    cd model_downloader && \
    python downloader.py --name face-detection-adas-0001 -o $MODELS && \
    python downloader.py --name age-gender-recognition-retail-0013 -o $MODELS && \
    python downloader.py --name emotions-recognition-retail-0003 -o $MODELS && \
    python downloader.py --name landmarks-regression-retail-0009 -o $MODELS && \
    python downloader.py --name face-detection-retail-0004 -o $MODELS && \
    python downloader.py --name face-reidentification-retail-0095 -o $MODELS

WORKDIR $HOME
RUN git clone -b ${IIKIM_GST_BRANCH} https://github.com/opencv/gst-video-analytics

ADD --chown=1000:1000 main.sh $HOME
RUN /bin/bash -c 'chmod +x $HOME/main.sh'
ADD --chown=1000:1000 mers_face_detection_and_classification.sh $HOME
RUN /bin/bash -c 'chmod +x $HOME/mers_face_detection_and_classification.sh'

ARG TARGET
ENV TARGET="${TARGET}"

ARG INPUT
ENV INPUT="${INPUT}"

ENTRYPOINT ["/home/mers-user/main.sh"]
CMD ["/home/mers-user/main.sh", "${TARGET}", "${INPUT}"]
