version: '3.7'
services:

  dlrs-restricted-zone-notifier-python:
    build:
      context: ./dlrs-restricted-zone-notifier-python/
      dockerfile: Dockerfile.dlrs-restricted-zone-notifier-python
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/dlrs-restricted-zone-notifier-python
    hostname: ${HOSTNAME}
    container_name: application-dlrs-restricted-zone-notifier-python
    privileged: true
    security_opt:
      - seccomp=unconfined
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    network_mode: host
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/mers-user/.Xauthority:rw
      - /usr/share/glib-2.0/schemas/gschemas.compiled:/usr/share/glib-2.0/schemas/gschemas.compiled
      - ../media/:/workspace/media

  dlrs-interactive-face-recognition-demo-python:
    build:
      context: ./dlrs-interactive-face-recognition-demo-python/
      dockerfile: Dockerfile.dlrs-interactive-face-recognition-demo-python
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/dlrs-interactive-face-recognition-demo-python
    hostname: ${HOSTNAME}
    container_name: application-dlrs-interactive-face-recognition-demo-python
    privileged: true
    security_opt:
      - seccomp=unconfined
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - STATSD_SERVER=${STATSD_SERVER:-172.17.0.1}
    network_mode: host
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/mers-user/.Xauthority:rw
      - /usr/share/glib-2.0/schemas/gschemas.compiled:/usr/share/glib-2.0/schemas/gschemas.compiled
      - ../media/:/workspace/media/

  dlrs-multicamera-multiperson-demo-python:
    build:
      context: ./dlrs-multicamera-multiperson-demo-python/
      dockerfile: Dockerfile.dlrs-multicamera-multiperson-demo-python
      args:
        - TARGET=${TARGET:-CPU}
        - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
    image: application/dlrs-multicamera-multiperson-demo-python
    hostname: ${HOSTNAME}
    container_name: application-dlrs-multicamera-multiperson-demo-python
    privileged: true
    security_opt:
      - seccomp=unconfined
    restart: always
    environment:
      - TZ=America/Mexico_City
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
      - TARGET=${TARGET:-CPU}
      - INPUT=${INPUT:-http://172.17.0.1:9081/?action=stream}
      - STATSD_SERVER=${STATSD_SERVER:-172.17.0.1}
    network_mode: host
    devices:
      - /dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/mers-user/.Xauthority:rw
      - /usr/share/glib-2.0/schemas/gschemas.compiled:/usr/share/glib-2.0/schemas/gschemas.compiled
      - ../media/:/workspace/media/
