FROM sysstacks/dlrs-tensorflow2-clearlinux

ARG IIKIM_DLRS_BRANCH=iikim-dlrs

RUN curl -o /workspace/video.mp4 https://raw.githubusercontent.com/intel-iot-devkit/sample-videos/master/face-demographics-walking-and-pause.mp4 && \
    git clone -b ${IIKIM_DLRS_BRANCH} https://github.com/bosques-urbanos/open_model_zoo.git && \
    cd ~/workspace/open_model_zoo/ && \
    git checkout -b 2019 origin/2019 && \
    cd model_downloader && \
    python downloader.py --name face-detection-retail-0004 -o ~/ && \
    python downloader.py --name landmarks-regression-retail-0009 -o ~/ && \
    python downloader.py --name face-reidentification-retail-0095 -o ~/

RUN cd ~/workspace/open_model_zoo/ && \
    git checkout ${IIKIM_DLRS_BRANCH} && \
    cd demos/python_demos/face_recognition_demo/ && \
    pip3 install -r requirements.txt && \
    pip3 install statsd

ADD --chown=1000:1000 main.sh /workspace/
RUN /bin/bash -c 'chmod +x /workspace/main.sh'

ARG TARGET
ENV TARGET="${TARGET}"

ARG INPUT
ENV INPUT="${INPUT}"

ARG STATSD_SERVER
ENV STATSD_SERVER="${STATSD_SERVER}"

ENTRYPOINT ["/workspace/main.sh"]
CMD ["/home/user/main.sh", "${TARGET}", "${INPUT}", "${STATSD_SERVER}"]
