FROM xe1gyq/openvino

MAINTAINER Abraham Arce "xe1gyq@gmail.com"

ARG OPENVINO_INSTALL=/opt/intel/openvino

ENV TIMEZONE America/Mexico_City
USER root
ENV HOME_USER /home/user

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl-dev \
    git && \
    rm -rf /var/lib/apt/lists/*

RUN chown -R user /home/user
USER user
WORKDIR /home/user

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh && \
    git clone https://github.com/intel-iot-devkit/restricted-zone-notifier-cpp.git && \
    mkdir restricted-zone-notifier-cpp/build/ && \
    cd restricted-zone-notifier-cpp/ && \
    bash ./setup.sh && \
    cd build/ && \
    cmake .. && \
    make"

ADD --chown=1000:1000 main.sh /home/user/
RUN /bin/bash -c 'chmod +x /home/user/main.sh'

RUN /bin/bash -c "source $OPENVINO_INSTALL/bin/setupvars.sh"
RUN echo "source $OPENVINO_INSTALL/bin/setupvars.sh" >> /home/user/.bashrc

ARG TARGET
ENV TARGET="${TARGET}"

ARG INPUT
ENV INPUT="${INPUT}"

ENTRYPOINT ["/home/user/main.sh"]
CMD ["/home/user/main.sh", "${TARGET}", "${INPUT}"]
